### ISSUE TITLE
Chrome Problem

### ISSUE THREAD

**Issue by Mrcdkk** [VIER-CognitiveVoice/reference-webrtc-client#1]
Hallo zusammen, 

ich verwende den webrtc-client in einer REACT Typescript App. 

In Firefox und Edge funktioniert ein Call einwandfrei. Im Chrome wird der Call nach einem Timeout abgelehnt. 

Hier der Code den ich aus einer React Componente aufrufe:

  ```
triggerControls(
    environment: any,
    resellerToken: any,
    destination: any,
    options: any
  ) {
    return new Promise((resolve, reject) => {
      fetchWebRtcAuthDetails(environment, resellerToken)
        .then((details) => {
          return setupSipClient(details, DEFAULT_TIMEOUT);
        })
        .then((telephony) => {
          const callTimeout = DEFAULT_TIMEOUT;
          const iceGatheringTimeout = DEFAULT_TIMEOUT;
          const headers = options?.telephony?.sipHeaders;
          return telephony
            .call(destination, callTimeout, iceGatheringTimeout, headers)
            .then((call) => {
              this._call = call;
              enableMediaStreamAudioInChrome(call.media);

              const [, controlsCleanup] = generateCallControls(call, options);
              call.callCompletion.then(() => {
                //              controlsCleanup()
                telephony.disconnect();
                this._call = null;
              });
              resolve(call);
            })
            .catch((e) => {
              telephony.disconnect();
              this._call = null;
              reject(e);
            });
        })
        .catch((e) => {
          reject(e);
        });
    });
  }

  call(): Promise<any> {
    const options = {
      ui: {
        anchor: undefined,
        position: {
          side: undefined,
          distance: [0, 0],
        },
        dark: undefined,
        keypad: undefined,
      },
      volume: {
        dtmfVolume: Number(0.03),
      },
    };

    return this.triggerControls(
      'https://cognitivevoice.io',
      'xxxxxxxxxxxxxxxxxxxxx',
      'xxxxxxxxxxxxxxxxxxxxx',
      options
    );
  }
```

Das Mikrofon ist in Chrome für die App freigeben. Im Netzwerk Protokoll ist auch nichts zu sehen.
Was mache ich falsch?

Viele Grüße,
Christian

**Comment by pschichtel** [comment]
@Mrcdkk ist es möglich die vollständige komponente zu teilen? macht das reproduzieren für mich einfacher.

**Comment by pschichtel** [comment]
@Mrcdkk reflektiert [das](https://github.com/VIER-CognitiveVoice/reference-webrtc-client/commit/fa1a6c03f4fe71afe60f0fe5adba349fa6e93574) etwa ihre anwendung?

**Comment by pschichtel** [comment]
Das problem ist der zu lange ICE gathering timeout (identisch zum call timeout). Der browser wartet bis zu 10 sekunden auf weitere ICE kanidaten, nachdem der letzte kandidate erkannt wurde. wenn der call timeout auch 10 sekunden ist, kann es dann dazu kommen, dass der anruf nicht über das ICE gathering hinaus kommt.

ich werde etwas doku einfügen.

dieser commit zeigt, wie ich es lokal behoben habe: https://github.com/VIER-CognitiveVoice/reference-webrtc-client/commit/0baea6a63633f305a2479d2bd3ed886a9267e241

die `DEFAULT_ICE_GATHERING_TIMEOUT` (250ms) hat sich bis her in meinen experimenten als ausreichend erwiesen.

**Comment by pschichtel** [comment]
wenn man die errors der promises logged sollte man im normalfall auch immer die entsprechende information in der konsole sehen:

![image](https://user-images.githubusercontent.com/526104/224112928-4b6fee18-3db6-4c2e-8aea-15f0c7bb1876.png)

**Comment by Mrcdkk** [comment]
Das war wohl mein Fehler. DEFAULT_ICE_GATHERING_TIMEOUT habe ich gar nicht verwendet. Wenn ich 

`const iceGatheringTimeout = DEFAULT_TIMEOUT;`
 
in 

`const iceGatheringTimeout = DEFAULT_ICE_GATHERING_TIMEOUT;`

ändere, funktioniert es auch in Chrome. 👍 

Danke für die schnelle Hilfe.
